Update padFootprint function
rapyuta-robotics/ros-navigation pull request #108
Opened 2024-12-25 05:43 UTC by Nisarg236

Previously this function was scaling the footprint with respect to the coordinate frame 0,0 which could result in distortion.
Now it scales with respect to the centroid of the footprint.

2024-12-25 10:40 UTC, corot approved these changes

2024-12-25 10:41 UTC, corot requested changes
3 things

The 1st example looks suspicious:  doesn't look like padded 10 cm but 2 or 3  :thinking: 

This looks similar to [this commit](https://github.com/corot/navigation/commit/7c4fbb9338178a240425f9b93efa994b0bb0f00d)
Do both provide the same result?  If so, this is simpler

Keep the formatting of the files you modify. i.e. never mix stiles

2024-12-26 02:49 UTC, Nisarg236 commented
> 3 things
> 
> The 1st example looks suspicious: doesn't look like padded 10 cm but 2 or 3 🤔
> 
> This looks similar to [this commit](https://github.com/corot/navigation/commit/7c4fbb9338178a240425f9b93efa994b0bb0f00d) Do both provide the same result? If so, this is simpler
> 
> Keep the formatting of the files you modify. i.e. never mix stiles

Hi you are right it wasnt 0.1 meters because it was scaling by percentage, I changed it to scale by meters and updated the image.
and now the functionality is the same as the one you shared.

2024-12-26 02:53 UTC, corot commented
> this commit

2024-12-26 02:55 UTC, corot commented
> Hi you are right it wasnt 0.1 meters because it was scaling by percentage, I changed it to scale by meters and updated the image. and now the functionality is the same as the one you shared.

So the outcome is now the same as with [this commit](https://github.com/corot/navigation/commit/7c4fbb9338178a240425f9b93efa994b0bb0f00d)?  
Then better to use the commit,,, as the logic is much simpler  :thinking:

2024-12-26 05:16 UTC, renan028 commented
> > Hi you are right it wasnt 0.1 meters because it was scaling by percentage, I changed it to scale by meters and updated the image. and now the functionality is the same as the one you shared.
> 
> So the outcome is now the same as with [this commit](https://github.com/corot/navigation/commit/7c4fbb9338178a240425f9b93efa994b0bb0f00d)? Then better to use the commit,,, as the logic is much simpler 🤔

@corot I think you are missing the part he calculates the centroid of the polygon.

2025-01-06 04:23 UTC, renan028 approved these changes

2025-01-06 04:23 UTC, renan028 commented on costmap_2d/src/footprint.cpp
> +  footprint_center.y = sum_y / footprint.size();
S: I think it makes sense to create a method `centroid` that returns `geometry_msgs::Point`

2025-01-06 04:23 UTC, renan028 commented on costmap_2d/src/footprint.cpp
> +    double distance = std::sqrt(dx * dx + dy * dy);
S: `std::hypot`

2025-01-06 04:26 UTC, renan028 commented
I think it makes sense to make a PR upstream:
https://github.com/ros-navigation/navigation2/blob/4e5d2dfc66cb75eb390d614d13e5b64efbf30284/nav2_costmap_2d/src/footprint.cpp#L145

2025-01-06 04:32 UTC, corot commented on costmap_2d/test/footprint_tests.cpp
> +  EXPECT_EQ( 1.66667f, footprint[0].x );
Q: do we really need to change round numbers?

2025-01-06 04:33 UTC, corot approved these changes
ok, as @renan028 explained, this implementation is superior to the one I mention

@Nisarg236 , you should consider open a PR to nav2, as this is a nice contribution

2025-01-06 13:08 UTC, Nisarg236 commented on costmap_2d/test/footprint_tests.cpp
> +  EXPECT_EQ( 1.66667f, footprint[0].x );
yes because otherwise it fails

2025-01-06 13:08 UTC, merged