prevent fast accelerations while turning to reduce risk of slip
rapyuta-robotics/ros-navigation pull request #16
Opened 2019-06-03 06:28 UTC by ChristofDubs

Disallows large forward accelerations during turns, to reduce risk of slip.

A bit of a hack, I would have preferred to take care of this by a trajectory scoring function, but that would require reverse engineering the acceleration in the scoring function (and generally be much larger changes).
I can do it now if we want; I would suggest to do that later.

2019-06-05 02:57 UTC, gauthamm requested changes

2019-06-05 02:57 UTC, gauthamm commented on base_local_planner/src/simple_trajectory_generator.cpp
> +        max_vel[0] = vel[0] + acc_lim[0] * sim_period_;
you don't constrain the velocity to a max factor in negative direction?

2019-06-05 03:05 UTC, gauthamm requested changes

2019-06-05 03:05 UTC, gauthamm commented on base_local_planner/src/simple_trajectory_generator.cpp
> +                acc_lim[0] * sim_period_ * (max_vel_th - 2.0 * std::fabs(vel[2])))));
fix normalisation

2019-06-05 11:50 UTC, bhuvanchandradv approved these changes

2019-06-06 04:08 UTC, gauthamm approved these changes

2019-06-06 04:11 UTC, merged