Jw map server poll
rapyuta-robotics/ros-navigation pull request #3
Opened 2019-02-07 06:38 UTC by Vuwij

2019-02-14 03:08 UTC, Vuwij commented
This is ready for review

2019-02-14 05:34 UTC, hendrik-skubch commented
It doesn't look like all comments were addressed

2019-02-14 05:43 UTC, hendrik-skubch requested changes

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/src/map_server.cpp
> +    } catch (YAML::InvalidScalar) {
const &

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/include/map_server/map_server.h
> +    MapServer(const std::string& fname);
explicit

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/include/map_server/image_loader.h
> - * Copyright (c) 2008, Willow Garage, Inc.
you can't just remove this copyright

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/include/map_server/map_server_updater.h
> +    MapServerUpdater(const std::string& _fname);
explicit

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/package.xml
> +    <version>2.0.0</version>
That's a big version jump

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/src/image_loader.cpp
> - * Copyright (c) 2008, Willow Garage, Inc.
see above

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/src/main.cpp
> +    } catch (std::runtime_error& e) {
const

2019-02-14 05:43 UTC, hendrik-skubch commented on map_server/src/map_server_updater.cpp
> +        : _fname(_fname) {
The mapserver should work even if there is no map_changed event.

2019-02-14 06:03 UTC, Vuwij reviewed
Issues are resolved, aside from the version jump.

It would attempt to find the map at the beginning, and if there is an error as the map is not found, it will print a warning that the map cannot be found, and then it will wait for the map_changed topic. See map_server_updater.cpp

2019-02-14 06:03 UTC, Vuwij commented on map_server/package.xml
> +    <version>2.0.0</version>
Well...

2019-02-14 06:17 UTC, gauthamm commented on map_server/CMakeLists.txt
>  find_package(PkgConfig REQUIRED)
already find packaged above

2019-02-14 06:17 UTC, gauthamm commented on map_server/CMakeLists.txt
> +    NAMES YAML_CPP
Is the names correct

2019-02-14 06:17 UTC, gauthamm commented on map_server/CMakeLists.txt
> +    yaml-cpp
shouldn't this be YAML_CPP_LIBRARY

2019-02-14 06:17 UTC, gauthamm commented on map_server/include/map_server/image_loader.h
> +void loadMapFromFile(nav_msgs::GetMap::Response* resp, const char* fname, const double res, const bool negate,
Why const? For double and bool const is unnecessary

2019-02-14 06:17 UTC, gauthamm commented on map_server/src/main.cpp
> +                MapServer ms(fname, res);
I assume this is deprecated usage. Do you want to still support it? If so please leave the deprecated usage helper Macro in the top of the file.

2019-02-14 06:17 UTC, gauthamm commented on map_server/src/main.cpp
> +    bool has_param = nh.getParam("use_local_map", use_local_map);
this line and the condition below do not make a difference. use_local_map is true by default anyway.

2019-02-14 06:17 UTC, gauthamm commented on map_server/src/main.cpp
> +            ros::spin();
ros::spin() is common and can be taken out of the if ... else

2019-02-14 06:17 UTC, gauthamm commented on map_server/src/map_server.cpp
> +MapServer::MapServer(const std::string& fname) {
I would recommend to have ros::NodeHandle here as a reference to make sure a node handle is initialised before creating an instance of MapServer

2019-02-14 06:17 UTC, gauthamm commented on map_server/src/map_server.cpp
> +    double occ_th = 0.65, free_th = 0.196;
set the default values using `private_nh.param()` to make it easier to read.

2019-02-14 06:17 UTC, gauthamm commented on map_server/src/map_server_updater.cpp
> +    } catch (const YAML::BadFile& ex) {
I don't think its a good practice to throw exceptions from a constructor. Might be better to have a separate init function for all yaml loading and catch them at a lower level than here.

2019-02-14 07:17 UTC, Vuwij commented on map_server/include/map_server/image_loader.h
> +void loadMapFromFile(nav_msgs::GetMap::Response* resp, const char* fname, const double res, const bool negate,
I thought using const was to just prevent re-assignment of the value

2019-02-14 07:22 UTC, Vuwij commented on map_server/src/main.cpp
> +            ros::spin();
The problem is that the destructor would be called.

2019-02-14 07:24 UTC, Vuwij commented on map_server/src/map_server.cpp
> +MapServer::MapServer(const std::string& fname) {
I;m not sure about this, a ros::NodeHandle is already a member inside the MapServer class, so it will automatically be created

2019-02-14 08:00 UTC, Vuwij commented on map_server/CMakeLists.txt
> +    yaml-cpp
fixed

2019-02-14 08:40 UTC, gauthamm commented on map_server/include/map_server/image_loader.h
> +void loadMapFromFile(nav_msgs::GetMap::Response* resp, const char* fname, const double res, const bool negate,
Yeah its fine, I thought it was a const ref

2019-02-14 08:41 UTC, gauthamm approved these changes

2019-02-15 08:15 UTC, hendrik-skubch approved these changes

2019-02-18 00:51 UTC, merged